force-app/main/default/objects/Account/fields/Income__c.field-meta.xml
<CustomField>
    <fullName>Income__c</fullName>
    <description>The amount of income this account expects to receive</description>
    <inlineHelpText>The amount of income this account expects to receive</inlineHelpText>
    <label>Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Income_Periodicity__c.field-meta.xml
<CustomField>
    <fullName>Income_Periodicity__c</fullName>
    <description>How often this account receives income</description>
    <inlineHelpText>How often this account receives income</inlineHelpText>
    <label>Income Periodicity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bank__c/Bank__c.object-meta.xml
<CustomObject>
    <description>Bank branch</description>
    <label>Bank</label>
    <nameField>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account this bank record is related to..</description>
    <inlineHelpText>The account this bank record is related to..</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Banks</relationshipLabel>
    <relationshipName>Banks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <description>The total balance for this bank account</description>
    <inlineHelpText>The total balance for this bank account</inlineHelpText>
    <label>Balance</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bank__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <label>Branch Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Barclays</fullName>
            </value>
            <value>
                <fullName>Monzo</fullName>
            </value>
            <value>
                <fullName>Natwest</fullName>
            </value>
            <value>
                <fullName>Nationwide</fullName>
            </value>
            <value>
                <fullName>Starling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountService.cls
public without sharing class AccountService {
    /*
     * @method  : getAccountDetails
     * @desc    : Return all information about an Account
     * @link    :
     */
    public static void getAccountDetails(RestRequest req, RestResponse res) {
        ErrorResponse errors;
        AccountServiceModel data = new AccountServiceModel();
        List<AccountServiceModel.Bank> banks = new List<AccountServiceModel.Bank>();

        Id accountId;

        try {
            // Get the account Id from URL
            accountId = req.params.get('accId');
        } catch (Exception e) {
            res.statusCode = 400;
            errors = new ErrorResponse('Bad Request');
            res.responseBody = Blob.valueOf(JSON.serializePretty(errors));

            return;
        }

        res.addHeader('Content-Type', 'application/json; charset=utf-8');

        try {
            Account acc = QueryUtils.getAccountDetails(accountId);

            for (Bank__c b : acc.Banks__r) {
                banks.add(
                    new AccountServiceModel.Bank(b.Branch_Name__c, b.Balance__c)
                );
            }

            data.id = acc.Id;
            data.income = acc.Income__c;
            data.incomePeriodicity = acc.Income_Periodicity__c;
            data.banks = banks;

            res.statusCode = 200;
            res.responseBody = Blob.valueOf(JSON.serializePretty(data));
        } catch (Exception e) {
            res.statusCode = 404;
            errors = new ErrorResponse('Account not found');
            res.responseBody = Blob.valueOf(JSON.serializePretty(errors));

            return;
        }
    }

    public class ErrorResponse {
        public String message;

        public errorResponse(string message) {
            this.message = message;
        }
    }
}