force-app/main/default/objects/Expenditure__c/Expenditure__c.object-meta.xml
<CustomObject>
    <description>A summary of the purchased item</description>
    <label>Expenditure</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Expenditure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenditures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expenditure__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The total cost of the item</description>
    <inlineHelpText>The total cost of the item</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expenditure__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>The category this expense record falls under</description>
    <inlineHelpText
    >The category this expense record falls under</inlineHelpText>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bills</fullName>
            </value>
            <value>
                <fullName>Charity</fullName>
            </value>
            <value>
                <fullName>Entertainment</fullName>
            </value>
            <value>
                <fullName>Food and Drink</fullName>
            </value>
            <value>
                <fullName>Groceries</fullName>
            </value>
            <value>
                <fullName>Holidays</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Person</fullName>
            </value>
            <value>
                <fullName>Personal Care</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ExpendituresService.cls
public without sharing class ExpendituresService {
    public final static Set<String> OrderByOption = new Set<String>{
        'ascending',
        'descending'
    };
    public final static Set<String> PeriodOption = new Set<String>{
        'daily',
        'monthly',
        'yearly'
    };
    public static ErrorResponse errors;
    public static String category;
    public static String period;
    public static String orderBy = 'ascending';
    public static Integer limiter = 10;

    /*
     * @method  : getExpenditures
     * @desc    : Return a list of expenditure items with the following optional
     *            filters applied, `category`, `period`, `orderBy`, `limit`
     * @link    : https://app.swaggerhub.com/apis/JasonFung6/Expenditure/1.0.0-oas3#/default/getListByFilters
     */
    public static void getExpenditures(RestRequest req, RestResponse res) {
        List<ExpendituresServiceModel> data = new List<ExpendituresServiceModel>();

        String accountId = req.params.get('accId');

        if (accountId == null || accountId == '') {
            res.statusCode = 400;
            errors = new ErrorResponse('Bad Request');
            res.responseBody = Blob.valueOf(JSON.serializePretty(errors));

            return;
        }

        // Make sure no invalid options from query params
        // are processed before we query the database.
        if (setOptionalQueryParams(req, res)) {
            res.addHeader('Content-Type', 'application/json; charset=utf-8');

            try {
                List<Expenditure__c> exps = QueryUtils.getExpendituresWithFilters(
                    accountId,
                    category,
                    period,
                    orderBy,
                    limiter
                );

                if (exps.size() > 0) {
                    for (Expenditure__c exp : exps) {
                        ExpendituresServiceModel esm = new ExpendituresServiceModel();

                        esm.id = exp.Id;
                        esm.amount = exp.Amount__c;
                        esm.createdDate = exp.CreatedDate.getTime();
                        esm.category = exp.Category__c;

                        data.add(esm);
                    }

                    res.statusCode = 200;
                    res.responseBody = Blob.valueOf(JSON.serializePretty(data));
                } else {
                    res.statusCode = 404;
                    errors = new ErrorResponse('Expenditure item(s) not found');
                    res.responseBody = Blob.valueOf(
                        JSON.serializePretty(errors)
                    );

                    return;
                }
            } catch (Exception e) {
                res.statusCode = 404;
                errors = new ErrorResponse('Expenditure item(s) not found');
                res.responseBody = Blob.valueOf(JSON.serializePretty(errors));

                return;
            }
        }
    }

    /**
     * @method  setOptionalQueryParams()
     * @desc    set query params if there's available data
     *          and the data matches the pre-defined options before
     *          assigning them to the class variables
     * @returns Boolean
     */
    private static Boolean setOptionalQueryParams(
        RestRequest req,
        RestResponse res
    ) {
        if (
            req.params.containsKey('category') &&
            req.params.get('category') != null &&
            req.params.get('category') != ''
        ) {
            category = req.params.get('category');
        }

        if (
            req.params.containsKey('period') &&
            req.params.get('period') != null &&
            req.params.get('period') != ''
        ) {
            String periodParam = req.params.get('period');

            // Ensure period value is a valid option
            if (PeriodOption.contains(periodParam)) {
                period = periodParam;
            } else {
                res.statusCode = 400;
                errors = new ErrorResponse('Bad Request, invalid option');
                res.responseBody = Blob.valueOf(JSON.serializePretty(errors));
                return false;
            }
        }

        if (
            req.params.containsKey('orderBy') &&
            req.params.get('orderBy') != null &&
            req.params.get('orderBy') != ''
        ) {
            String orderByParam = req.params.get('orderBy');

            // Ensure orderBy value is a valid option
            if (OrderByOption.contains(orderByParam)) {
                orderBy = orderByParam;
            } else {
                res.statusCode = 400;
                errors = new ErrorResponse('Bad Request, invalid option');
                res.responseBody = Blob.valueOf(JSON.serializePretty(errors));
                return false;
            }
        }

        if (
            req.params.containsKey('limit') &&
            req.params.get('limit') != null &&
            req.params.get('limit') != ''
        ) {
            limiter = Integer.valueof(req.params.get('limit'));
        }

        return true;
    }

    public class ErrorResponse {
        public String message;

        public errorResponse(string message) {
            this.message = message;
        }
    }
}