force-app/main/default/objects/Bank__c/Bank__c.object-meta.xml
<CustomObject>
    <description>Bank branch</description>
    <label>Bank</label>
    <nameField>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <label>Branch Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Barclays</fullName>
            </value>
            <value>
                <fullName>Monzo</fullName>
            </value>
            <value>
                <fullName>Natwest</fullName>
            </value>
            <value>
                <fullName>Nationwide</fullName>
            </value>
            <value>
                <fullName>Starling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expenditure__c/Expenditure__c.object-meta.xml
<CustomObject>
    <description>A summary of the purchased item</description>
    <label>Expenditure</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Expenditure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenditures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expenditure__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The total cost of the item</description>
    <inlineHelpText>The total cost of the item</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expenditure__c/fields/Bank__c.field-meta.xml
<CustomField>
    <fullName>Bank__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The related bank this expense record has withdrawn funds from</description>
    <inlineHelpText>The related bank this expense record has withdrawn funds from</inlineHelpText>
    <label>Bank</label>
    <referenceTo>Bank__c</referenceTo>
    <relationshipLabel>Expenditures</relationshipLabel>
    <relationshipName>Expenditures</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expenditure__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>The category this expense record falls under</description>
    <inlineHelpText
    >The category this expense record falls under</inlineHelpText>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bills</fullName>
            </value>
            <value>
                <fullName>Charity</fullName>
            </value>
            <value>
                <fullName>Entertainment</fullName>
            </value>
            <value>
                <fullName>Food and Drink</fullName>
            </value>
            <value>
                <fullName>Groceries</fullName>
            </value>
            <value>
                <fullName>Holidays</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Person</fullName>
            </value>
            <value>
                <fullName>Personal Care</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expenditure__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A short description about this expenditure record</description>
    <inlineHelpText>A short description about this expenditure record</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/ExpenditureService.cls
public without sharing class ExpenditureService {
    /*
     * @method  : getExpenditure
     * @desc    : Return a single expenditure item
     * @link    : https://app.swaggerhub.com/apis/JasonFung6/Expenditure/1.0.0-oas3#/default/getById
     */
    public static void getExpenditure(RestRequest req, RestResponse res) {
        ErrorResponse errors;
        ExpenditureServiceModel data = new ExpenditureServiceModel();

        Id accountId;
        Id expenditureId;

        try {
            // Get the account and expenditure Id from URL
            accountId = req.params.get('accId');
            expenditureId = req.params.get('expId');
        } catch (Exception e) {
            res.statusCode = 400;
            errors = new ErrorResponse('Bad Request');
            res.responseBody = Blob.valueOf(JSON.serializePretty(errors));

            return;
        }

        res.addHeader('Content-Type', 'application/json; charset=utf-8');

        try {
            Account acc = QueryUtils.getAccountById(accountId);
            Expenditure__c exp = QueryUtils.getExpenditureByAccIdAndExpId(
                accountId,
                expenditureId
            );

            // Assign queried data to wrapper class
            data.id = exp.Id;
            data.bank = exp.Bank__r.Branch_Name__c;
            data.amount = exp.Amount__c;
            data.createdDate = exp.CreatedDate.getTime(); // Convert DateTime to Unix timestamp
            data.receiptURL = '';
            data.category = exp.Category__c;
            data.description = exp.Description__c;

            res.statusCode = 200;
            res.responseBody = Blob.valueOf(JSON.serializePretty(data));
        } catch (Exception e) {
            res.statusCode = 404;
            errors = new ErrorResponse('Expenditure item not found');
            res.responseBody = Blob.valueOf(JSON.serializePretty(errors));

            return;
        }
    }

    public class ErrorResponse {
        public String message;

        public errorResponse(string message) {
            this.message = message;
        }
    }
}