force-app/main/default/objects/Bank__c/Bank__c.object-meta.xml
<CustomObject>
    <description>Bank branch</description>
    <label>Bank</label>
    <nameField>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account this bank record is related to..</description>
    <inlineHelpText>The account this bank record is related to..</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Banks</relationshipLabel>
    <relationshipName>Banks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expenditure__c/Expenditure__c.object-meta.xml
<CustomObject>
    <description>A summary of the purchased item</description>
    <label>Expenditure</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Expenditure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenditures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expenditure__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The account this expense record is related to</description>
    <inlineHelpText>The account this expense record is related to</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Expenditures</relationshipLabel>
    <relationshipName>Expenditures</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expenditure__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The total cost of the item</description>
    <inlineHelpText>The total cost of the item</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expenditure__c/fields/Bank__c.field-meta.xml
<CustomField>
    <fullName>Bank__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The related bank this expense record has withdrawn funds from</description>
    <inlineHelpText>The related bank this expense record has withdrawn funds from</inlineHelpText>
    <label>Bank</label>
    <referenceTo>Bank__c</referenceTo>
    <relationshipLabel>Expenditures</relationshipLabel>
    <relationshipName>Expenditures</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expenditure__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>The category this expense record falls under</description>
    <inlineHelpText
    >The category this expense record falls under</inlineHelpText>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bills</fullName>
            </value>
            <value>
                <fullName>Charity</fullName>
            </value>
            <value>
                <fullName>Entertainment</fullName>
            </value>
            <value>
                <fullName>Food and Drink</fullName>
            </value>
            <value>
                <fullName>Groceries</fullName>
            </value>
            <value>
                <fullName>Holidays</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Person</fullName>
            </value>
            <value>
                <fullName>Personal Care</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expenditure__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A short description about this expenditure record</description>
    <inlineHelpText>A short description about this expenditure record</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/QueryUtils.cls
/**
 * @class   QueryUtils
 * @desc    Utilities class to hold SOQL related methods
 * @date    22/12/2020
 */
public without sharing class QueryUtils {
    public static Account getAccountById(Id accId) {
        return [SELECT Id FROM Account WHERE Id = :accId];
    }

    public static Expenditure__c getExpenditureByAccIdAndExpId(
        Id accId,
        Id expId
    ) {
        return [
            SELECT
                Id,
                Amount__c,
                Bank__r.Name,
                Category__c,
                CreatedDate,
                Description__c
            FROM Expenditure__c
            WHERE Account__c = :accId AND Id = :expId
        ];
    }

    public static List<Expenditure__c> getExpendituresWithFilters(Id accId, String category, String period, String orderBy, Integer limiter) {
        String query = 'SELECT Id, Amount__c, Category__c, CreatedDate FROM Expenditure__c WHERE Account__c = :accId ';

        if (category != null) {
            query += 'AND Category__c = :category ';
        }

        if (period != null) {
            if (period == 'daily') {
                query += 'AND CreatedDate = TODAY ';
            }

            if (period == 'monthly') {
                query += 'AND CreatedDate = THIS_MONTH ';
            }

            if (period == 'yearly') {
                query += 'AND CreatedDate = THIS_YEAR ';
            }
        }

        if (orderBy != null) {
            if (orderBy == 'ascending') {
                query += 'ORDER BY CreatedDate ASC ';
            } else if (orderBy == 'descending') {
                query += 'ORDER BY CreatedDate DESC ';
            }
        }

        if (limiter != null) {
            query += 'LIMIT :limiter ';
        }

        return Database.query(query);
    }
}